{
 "title": "IOTPaaS [Whitebox Appplication Metrics]",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "iotpaas-message-producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "heap memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"192.168.1.50:31199\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"192.168.1.50:31199\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=\"192.168.1.50:31199\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=\"192.168.1.50:31199\"}",
     "legendFormat": "sys"
    },
    {
     "expr": "go_memstats_heap_objects{instance=\"192.168.1.50:31199\"}",
     "legendFormat": "objects"
    }
   ]
  },
  {
   "title": "stack memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=\"192.168.1.50:31199\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{instance=\"192.168.1.50:31199\"}",
     "legendFormat": "sys"
    },
    {
     "expr": "go_memstats_alloc_bytes{instance=\"192.168.1.50:31199\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=\"192.168.1.50:31199\"}[1m])",
     "legendFormat": "alloc total"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction{instance=\"192.168.1.50:31199\"}",
     "legendFormat": "gc"
    },
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"192.168.1.50:31199\"}[1m])",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "http duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(iotpaas_message_producer_http_duration_seconds_sum{instance=\"192.168.1.50:31199\",path=\"/api/v1/streamdata\"}[1m]))",
     "legendFormat": "duration avg"
    }
   ]
  },
  {
   "title": "requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "iotpaas_message_producer_http_duration_seconds_count{instance=\"192.168.1.50:31199\",path=\"/api/v1/streamdata\"}"
    }
   ]
  },
  {
   "title": "isalive http duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(iotpaas_message_producer_http_duration_seconds_sum{instance=\"192.168.1.50:31199\",path=\"/api/v2/sys/info/isalive\"}[1m])",
     "legendFormat": "isalive"
    }
   ]
  },
  {
   "title": "http duration (seconds) quantile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "iotpaas_message_producer_http_duration_seconds_bucket{instance=\"192.168.1.50:31199\",path=\"/api/v1/streamdata\", le=\"0.005\"}",
     "legendFormat": "0.005"
    },
    {
     "expr": "iotpaas_message_producer_http_duration_seconds_bucket{instance=\"192.168.1.50:31199\",path=\"/api/v1/streamdata\", le=\"0.025\"}",
     "legendFormat": "0.025"
    },
    {
     "expr": "iotpaas_message_producer_http_duration_seconds_bucket{instance=\"192.168.1.50:31199\",path=\"/api/v1/streamdata\", le=\"0.1\"}",
     "legendFormat": "0.1"
    },
    {
     "expr": "iotpaas_message_producer_http_duration_seconds_bucket{instance=\"192.168.1.50:31199\",path=\"/api/v1/streamdata\", le=\"1\"}",
     "legendFormat": "1"
    }
   ]
  },
  { "title": "iotpaas-message-consumer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "heap memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"192.168.1.50:9000\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"192.168.1.50:9000\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=\"192.168.1.50:9000\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=\"192.168.1.50:9000\"}",
     "legendFormat": "sys"
    },
    {
     "expr": "go_memstats_heap_objects{instance=\"192.168.1.50:9000\"}",
     "legendFormat": "objects"
    }
   ]
  },
  {
   "title": "stack memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=\"192.168.1.50:9000\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{instance=\"192.168.1.50:9000\"}",
     "legendFormat": "sys"
    },
    {
     "expr": "go_memstats_alloc_bytes{instance=\"192.168.1.50:9000\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=\"192.168.1.50:9000\"}[1m])",
     "legendFormat": "alloc total"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction{instance=\"192.168.1.50:9000\"}",
     "legendFormat": "gc"
    },
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"192.168.1.50:9000\"}[1m])",
     "legendFormat": "total"
    }
   ]
  }
 ]
}