apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "resource-limits"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "6000m"
        memory: "6Gi"
      min:
        cpu: "10m"
        memory: "6Mi"
    - type: "Container"
      # it is very import to include a default otherwise builder and deployer pods will not run
      default:
        cpu: "200m"
        memory: "750Mi"
      defaultRequest:
        cpu: "200m"
        memory: "375Mi"
      max:
        cpu: "6000m"
        memory: "6Gi"
      min:
        cpu: "10m"
        memory: "3Mi"
