{
 "title": "TCPOD [Whitebox Appplication Metrics]",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "golang-simple-streamdataservice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "heap memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_heap_inuse_bytes{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
       "legendFormat": "usage"
      },
      {
       "expr": "go_memstats_heap_alloc_bytes{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
       "legendFormat": "alloc"
      },
      {
       "expr": "go_memstats_heap_idle_bytes{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
       "legendFormat": "idle"
      },
      {
       "expr": "go_memstats_heap_sys_bytes{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
       "legendFormat": "sys"
      },
      {
       "expr": "go_memstats_heap_objects{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
       "legendFormat": "objects"
      }
     ]
    },
    {
     "title": "stack memory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_stack_inuse_bytes{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
       "legendFormat": "usage"
      },
      {
       "expr": "go_memstats_stack_sys_bytes{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
       "legendFormat": "sys"
      },
      {
       "expr": "go_memstats_alloc_bytes{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
       "legendFormat": "alloc"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}[1m])",
       "legendFormat": "alloc total"
      }
     ]
    },
    {
     "title": "cpu",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "go_memstats_gc_cpu_fraction{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
       "legendFormat": "gc"
      },
      {
       "expr": "rate(process_cpu_seconds_total{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}[1m])",
       "legendFormat": "total"
      }
     ]
    },
    {
     "title": "http duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(rate(http_duration_seconds_sum{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\",path=\"/api/v1/streamdata\"}[1m]))",
       "legendFormat": "duration avg"
      }
     ]
    },
    {
     "title": "requests",
     "type": "stat",
     "gridPos": { "h": 9, "w": 4, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "http_duration_seconds_count{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\",path=\"/api/v1/streamdata\"}"
      }
     ]
    },
    {
     "title": "isalive http duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 4, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(http_duration_seconds_sum{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\",path=\"/api/v1/sys/info/isalive\"}[1m])",
       "legendFormat": "isalive"
      }
     ]
    },
    {
     "title": "http duration (seconds) quantile",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "http_duration_seconds_bucket{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\",path=\"/api/v1/streamdata\", le=\"0.005\"}",
       "legendFormat": "0.005"
      },
      {
       "expr": "http_duration_seconds_bucket{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\",path=\"/api/v1/streamdata\", le=\"0.025\"}",
       "legendFormat": "0.025"
      },
      {
       "expr": "http_duration_seconds_bucket{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\",path=\"/api/v1/streamdata\", le=\"0.1\"}",
       "legendFormat": "0.1"
      },
      {
       "expr": "http_duration_seconds_bucket{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\",path=\"/api/v1/streamdata\", le=\"1\"}",
       "legendFormat": "1"
      }
     ]
    }
   ]
  },
  {
   "title": "golang-second-streamdataservice",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "heap memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
     "legendFormat": "idle"
    },
    {
     "expr": "go_memstats_heap_sys_bytes{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
     "legendFormat": "sys"
    },
    {
     "expr": "go_memstats_heap_objects{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
     "legendFormat": "objects"
    }
   ]
  },
  {
   "title": "stack memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_inuse_bytes{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
     "legendFormat": "usage"
    },
    {
     "expr": "go_memstats_stack_sys_bytes{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
     "legendFormat": "sys"
    },
    {
     "expr": "go_memstats_alloc_bytes{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
     "legendFormat": "alloc"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}[1m])",
     "legendFormat": "alloc total"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_gc_cpu_fraction{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}",
     "legendFormat": "gc"
    },
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\"}[1m])",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "http duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(http_duration_seconds_sum{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\",path=\"/api/v1/streamdata\"}[1m]))",
     "legendFormat": "duration avg"
    }
   ]
  },
  {
   "title": "requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "http_duration_seconds_count{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\",path=\"/api/v1/streamdata\"}"
    }
   ]
  },
  {
   "title": "isalive http duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_duration_seconds_sum{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\",path=\"/api/v1/sys/info/isalive\"}[1m])",
     "legendFormat": "isalive"
    }
   ]
  },
  {
   "title": "http duration (seconds) quantile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "http_duration_seconds_bucket{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\",path=\"/api/v1/streamdata\", le=\"0.005\"}",
     "legendFormat": "0.005"
    },
    {
     "expr": "http_duration_seconds_bucket{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\",path=\"/api/v1/streamdata\", le=\"0.025\"}",
     "legendFormat": "0.025"
    },
    {
     "expr": "http_duration_seconds_bucket{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\",path=\"/api/v1/streamdata\", le=\"0.1\"}",
     "legendFormat": "0.1"
    },
    {
     "expr": "http_duration_seconds_bucket{instance=\"iotpaas-message-producer.iotpaas.svc.cluster.local:9000\",path=\"/api/v1/streamdata\", le=\"1\"}",
     "legendFormat": "1"
    }
   ]
  }
 ]
}