{
 "title": "TCPROD [Log Monitoring & Alerts]",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "kubectl alert",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "alerts",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "bucketAggs": [
        { "field": "@timestamp", "id": "1", "settings": { "interval": "10s" }, "type": "date_histogram" }
       ],
       "metrics": [
        {
         "hide": false,
         "id": "1",
         "type": "count"
        }
       ],
       "query": "kubernetes.namespace_name:\"custom-alert\" AND (message:*error* OR message:*fail*) ",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "kubectl events error logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "logs",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "kubernetes.namespace_name:\"custom-alert\" AND (message:*error* OR message:*fail*) ",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "kubectl events all logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "logs",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "kubernetes.namespace_name:\"custom-alert\" ",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "all microservice alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "all microservice alerts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "1", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "kubernetes.namespace_name:\"tcprod-apps\"  AND (message:*error* OR message:*fail*)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "golang-simple-echoservice error logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "logs",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "kubernetes.namespace_name:\"tcprod-apps\" AND kubernetes.container_name:\"golang-simple-echoservice\" AND (message:*error* OR message:*fail*)",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "golang-second-echoservice error logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "logs",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "metrics": [
        { "id": "1", "settings": { "size": "500" }, "type": "raw_data" }
       ],
       "query": "kubernetes.namespace_name:\"tcprod-apps\" AND kubernetes.container_name:\"golang-second-echoservice\" AND (message:*error* OR message:*fail*)",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}