apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: tcprod-prometheus
  name: tcprod-prometheus
  namespace: tcprod-pg
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    k8s-app: tcprod-prometheus
  sessionAffinity: None
  type: ClusterIP
